### ISSUE TITLE
Navigator shows yellow bottom bar on selection

### ISSUE THREAD

**Issue by Phillip3** [echo-labs-team/the-resonance-project#24]
notice the yellow bar below "Media"? That shouldn't be there.
![Screenshot_1570407771](https://user-images.githubusercontent.com/8754882/66278484-3c6f2e80-e85e-11e9-8bd2-55f3166f78d2.png)

**Comment by dereckquock** [comment]
this was fixed in that last PR https://github.com/Phillip3/the-resonance-project/pull/22/files#diff-bcae25d87701145be5670f959508716dR218
