### ISSUE TITLE
Groups title is not shrinking to fit the available space

### ISSUE THREAD

**Issue by Phillip3** [echo-labs-team/the-resonance-project#257]
**Describe the bug**
Groups title is not shrinking to fit the available space and truncation without `...`

**To Reproduce**
1. Go to Groups
2. Scroll down to Hope Project for At Home Educators (Parents and

**Expected behavior**
Either the text resizes to fit into the available space or we show `...`s

**Screenshots**
![Screenshot_20200616-202001_EchoChurch](https://user-images.githubusercontent.com/8754882/84851846-30a05280-b010-11ea-8fa4-bfeb7e54194b.jpg)
![Screenshot_20200616-202005_EchoChurch](https://user-images.githubusercontent.com/8754882/84851841-2da56200-b010-11ea-8d41-d89517f800c6.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s10 
 - OS: android version 10

**Additional context**
N/A

**Comment by Phillip3** [comment]
Maybe the filter has something to do with it (if it's not reproducing on the emulator)

**Comment by dereckquock** [comment]
is this still an issue?
