### ISSUE TITLE
Prayer request button needs a correct link

### ISSUE THREAD

**Issue by Phillip3** [echo-labs-team/the-resonance-project#27]

**Comment by nickkurat** [comment]
@Phillip3 @dereckquock here is the link to use for the prayer requests button (below). If possible, let's make this form link updatable without having to submit an update to the app store (not sure if react native helps do that out of the box)

https://docs.google.com/forms/d/e/1FAIpQLScXKoHyYZnqe7HgI0W9ZYYZllrXkDLXQv8pJKmH15oOyRrG0Q/viewform

**Comment by dereckquock** [comment]
> @Phillip3 @dereckquock here is the link to use for the prayer requests button (below). If possible, let's make this form link updatable without having to submit an update to the app store (not sure if react native helps do that out of the box)

what do you mean by "updatable"? you mean update the form? can't you just update the google form then?

**Comment by nickkurat** [comment]
@dereckquock sorry for the delay - the idea is to be able to quickly update the links assigned to the buttons without having to resubmit the app. I.e. for situations where we need to use a different form or introduce rock-powered forms etc. 

Not critical for the first launch, but thought it would be a good practice to include this flexibility from the first version.

**Comment by Phillip3** [comment]
@nickkurat what we’re seeing experimentally is that the only time you need to update the app in the store is if you update dependencies. So most cosmetic and light functional changes will have no problem being changed and pushed from our local machines.

**Comment by nickkurat** [comment]
Ok sounds good, thanks Phillip. Just to double check - does this mean that button links also would be able to be updated without resubmitting an update to the app stores?

**Comment by Phillip3** [comment]
Yep! Should be true. Right now, all we have to do is run “expo publish” from our machines and it updates basically everything about the app.

**Comment by nickkurat** [comment]
Ok cool, thanks! I started loving react native even more now 😁

**Comment by Phillip3** [comment]
😐
